### ISSUE TITLE
[建议] 同步进行Internet Archive备份

### ISSUE THREAD

**Issue by CSharperMantle** [riccaxricca/wyswd#3]
Internet Archive ([web.archive.org](https://web.archive.org/)) 能够作为阻止takedown的又一道防线，但是其对GH页面爬取收录较慢。建议手动对每个页面进行提交存档，作为备份。

**Comment by riccaxricca** [comment]
多谢你的建议，我把 riccaxricca@b4e647b 打包下载然后传到这个网站了：
https://archive.org/details/wyswd-b4e647b
