### ISSUE TITLE
世界树.(在建)诚信邀请各位理查参观

### ISSUE THREAD

**Issue by hoyolife** [riccaxricca/wyswd#5]
[世界树.入口1](http://hoyo.life/)
[世界树.入口2](https://hoyolife.github.io/)

**Comment by riccaxricca** [comment]
佬，你可以把我这个readme里两个事件的markdown拿过去直接当两份吃瓜投稿吗？

**Comment by hoyolife** [comment]
在弄了，网站服务器问题挺大，估计先弄好那边再说。
请问一下世界树.的网址可以加到READ.MD里面么

**Comment by riccaxricca** [comment]
没问题但点开链接是`ERR_TOO_MANY_REDIRECTS`，等你搞好了踢我一下

**Comment by hoyolife** [comment]
![image](https://github.com/riccaxricca/wyswd/assets/140965877/87d1ce31-8422-4a23-84b6-3f58d84be33a)
为啥我这里是正常的..

**Comment by riccaxricca** [comment]
我依然是`ERR_TOO_MANY_REDIRECTS`，你可以试着debug一下，我用的chrome：
![屏幕截图 2023-07-31 120528](https://github.com/riccaxricca/wyswd/assets/100435961/5b18d6eb-850d-45ac-a14f-e297205fbce5)
![屏幕截图 2023-07-31 120511](https://github.com/riccaxricca/wyswd/assets/100435961/ddb8b48c-6522-40c9-aacb-655bdc139625)

**Comment by hoyolife** [comment]
可能运营商问题，也有可能浏览器问题....无痕模式看看？我这换了三个网络，设备也换了手机和电脑都可以正常访问

**Comment by riccaxricca** [comment]
> 可能运营商问题，也有可能浏览器问题....无痕模式看看？我这换了三个网络，设备也换了手机和电脑都可以正常访问

ok，把世界树加到readme里边了 riccaxricca@220d5b8 
你有空可以找找原因，我还是一直报上面的错打不开页面

**Comment by hoyolife** [comment]
现在应该是可以了，cf那边搞定了设置，服务器时间也同步了。
![image](https://github.com/riccaxricca/wyswd/assets/140965877/44e5ae70-9c04-4c1c-bb11-c2ccf4c41613)

**Comment by riccaxricca** [comment]
> 现在应该是可以了，cf那边搞定了设置，服务器时间也同步了。

试了下，可以了
